/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author nschu
 */
public class CarritoUI extends javax.swing.JFrame {

    static ClienteUI  cliente = new ClienteUI();
    static ArrayList<Articulos> articuloss = new ArrayList<>();
    static int [] articulos = new int [6];
    String resumen ;
    /*
     En este arreglo guardo las veces que le dan click comparar al producto
     posicion o -> Articulo 1
     posicion 1 -> Articulo 2


     */

    public CarritoUI(int [] arreglo) {
        setResizable(false);
         setLocationRelativeTo(null);
        initComponents();
        for (int i=0; i<6 ; i++){
            articulos[i]=arreglo[i];
        }
        inicializar();
        System.out.println("Producto: "+articulos[0]);
        System.out.println("Imagen: "+articuloss.get(0).getImagen());
        //System.out.println("Numero: "+cliente.articulos1.get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void inicializar(){
        articuloss= cliente.obtenerArticulos();
        System.out.println("Click en boton1: "+articulos[0]);
/*
        for (int i=0; i<articulos.length; i++){
            if (articulos[i]!=0){

                ImageIcon imagen1 = new ImageIcon(getClass().getResource(articuloss.get(0).getImagen()));
                Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(imgProducto1.getWidth(), imgProducto1.getHeight(), Image.SCALE_SMOOTH));
                imgProducto1.setIcon(fondo1);
                this.repaint();

                ImageIcon imagen2 = new ImageIcon(getClass().getResource(articuloss.get(1).getImagen()));
                Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(imgProducto2.getWidth(), imgProducto2.getHeight(), Image.SCALE_SMOOTH));
                imgProducto2.setIcon(fondo2);
                this.repaint();

                ImageIcon imagen3 = new ImageIcon(getClass().getResource(articuloss.get(2).getImagen()));
                Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(imgProducto3.getWidth(), imgProducto3.getHeight(), Image.SCALE_SMOOTH));
                imgProducto3.setIcon(fondo3);
                this.repaint();

                ImageIcon imagen4 = new ImageIcon(getClass().getResource(articuloss.get(3).getImagen()));
                Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(imgProducto4.getWidth(), imgProducto4.getHeight(), Image.SCALE_SMOOTH));
                imgProducto4.setIcon(fondo4);
                this.repaint();

                ImageIcon imagen5 = new ImageIcon(getClass().getResource(articuloss.get(4).getImagen()));
                Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(imgProducto5.getWidth(), imgProducto5.getHeight(), Image.SCALE_SMOOTH));
                imgProducto5.setIcon(fondo5);
                this.repaint();

                ImageIcon imagen6 = new ImageIcon(getClass().getResource(articuloss.get(5).getImagen()));
                Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(imgProducto6.getWidth(), imgProducto6.getHeight(), Image.SCALE_SMOOTH));
                imgProducto6.setIcon(fondo6);
                this.repaint();

            }
        }

*/


  if (articulos[0]!=0){
                ImageIcon imagen1 = new ImageIcon(getClass().getResource(articuloss.get(0).getImagen()));
                Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(imgProducto1.getWidth(), imgProducto1.getHeight(), Image.SCALE_SMOOTH));
                imgProducto1.setIcon(fondo1);
                this.repaint();

                String resumen1 = "\nProducto 1: "+articuloss.get(0).getNombre()+"\nPrecio: "+articuloss.get(0).getPrecio()+
                        "\nDescuento: "+articuloss.get(0).getDescuento()+"\nStock: "+articuloss.get(0).getStock()+
                        "\nNo Articulos: "+articulos[0]+"\n";
                System.out.println(resumen1);
                jTextArea1.append(resumen1);
                resumen= new StringBuilder().append(resumen).append(resumen1).toString();
            }


            if (articulos[1]!=0){
                ImageIcon imagen2 = new ImageIcon(getClass().getResource(articuloss.get(1).getImagen()));
                Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(imgProducto2.getWidth(), imgProducto2.getHeight(), Image.SCALE_SMOOTH));
                imgProducto2.setIcon(fondo2);


                this.repaint();

                String resumen1 = "\nProducto 2: "+articuloss.get(1).getNombre()+"\nPrecio: "+articuloss.get(1).getPrecio()+
                        "\nDescuento: "+articuloss.get(1).getDescuento()+"\nStock: "+articuloss.get(1).getStock()+
                        "\nNo Articulos: "+articulos[1]+"\n";
                System.out.println(resumen1);
                jTextArea1.append(resumen1);


            }


if (articulos[2]!=0){
    ImageIcon imagen3 = new ImageIcon(getClass().getResource(articuloss.get(2).getImagen()));
    Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(imgProducto3.getWidth(), imgProducto3.getHeight(), Image.SCALE_SMOOTH));
    imgProducto3.setIcon(fondo3);
    this.repaint();

    String resumen1 = "\nProducto 3: "+articuloss.get(2).getNombre()+"\nPrecio: "+articuloss.get(2).getPrecio()+
            "\nDescuento: "+articuloss.get(2).getDescuento()+"\nStock: "+articuloss.get(2).getStock()+
            "\nNo Articulos: "+articulos[2]+"\n";
    System.out.println(resumen1);
    jTextArea1.append(resumen1);
}


    if(articulos[3]!=0){
        ImageIcon imagen4 = new ImageIcon(getClass().getResource(articuloss.get(3).getImagen()));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(imgProducto4.getWidth(), imgProducto4.getHeight(), Image.SCALE_SMOOTH));
        imgProducto4.setIcon(fondo4);
        this.repaint();

        String resumen1 = "\nProducto 4: "+articuloss.get(3).getNombre()+"\nPrecio: "+articuloss.get(3).getPrecio()+
                "\nDescuento: "+articuloss.get(3).getDescuento()+"\nStock: "+articuloss.get(3).getStock()+
                "\nNo Articulos: "+articulos[3]+"\n";
        System.out.println(resumen1);
        jTextArea1.append(resumen1);
    }

    if(articulos[4]!=0){
        ImageIcon imagen5 = new ImageIcon(getClass().getResource(articuloss.get(4).getImagen()));
        Icon fondo5 = new ImageIcon(imagen5.getImage().getScaledInstance(imgProducto5.getWidth(), imgProducto5.getHeight(), Image.SCALE_SMOOTH));
        imgProducto5.setIcon(fondo5);
        this.repaint();

        String resumen1 = "\nProducto 5: "+articuloss.get(4).getNombre()+"\nPrecio: "+articuloss.get(4).getPrecio()+
                "\nDescuento: "+articuloss.get(4).getDescuento()+"\nStock: "+articuloss.get(4).getStock()+
                "\nNo Articulos: "+articulos[4]+"\n";
        System.out.println(resumen1);
        jTextArea1.append(resumen1);
    }

    if (articulos[5]!=0){
        ImageIcon imagen6 = new ImageIcon(getClass().getResource(articuloss.get(5).getImagen()));
        Icon fondo6 = new ImageIcon(imagen6.getImage().getScaledInstance(imgProducto6.getWidth(), imgProducto6.getHeight(), Image.SCALE_SMOOTH));
        imgProducto6.setIcon(fondo6);
        this.repaint();

        String resumen1 = "\nProducto 6: "+articuloss.get(5).getNombre()+"\nPrecio: "+articuloss.get(5).getPrecio()+
                "\nDescuento: "+articuloss.get(5).getDescuento()+"\nStock: "+articuloss.get(5).getStock()+
                "\nNo Articulos: "+articulos[5]+"\n";
        System.out.println(resumen1);
        jTextArea1.append(resumen1);
    }








    }

    private void initComponents() {

        panel = new javax.swing.JPanel();
        tituloCarrito = new javax.swing.JLabel();
        imgProducto1 = new javax.swing.JLabel();
        imgProducto2 = new javax.swing.JLabel();
        imgProducto3 = new javax.swing.JLabel();
        imgProducto4 = new javax.swing.JLabel();
        imgProducto5 = new javax.swing.JLabel();
        imgProducto6 = new javax.swing.JLabel();
        tituloCarrito1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnComprar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloCarrito.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tituloCarrito.setText("Su carrito:");

        tituloCarrito1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tituloCarrito1.setText("Resumen de Compra:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.append(resumen);

        btnComprar.setText("Comprar");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }


        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(imgProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(imgProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(tituloCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(btnComprar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

          /* Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoUI().setVisible(true);
            }


        });
        */



    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel imgProducto1;
    private javax.swing.JLabel imgProducto2;
    private javax.swing.JLabel imgProducto3;
    private javax.swing.JLabel imgProducto4;
    private javax.swing.JLabel imgProducto5;
    private javax.swing.JLabel imgProducto6;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel tituloCarrito;
    private javax.swing.JLabel tituloCarrito1;
    // End of variables declaration//GEN-END:variables
}
